### ISSUE TITLE
Local Development Environment

### ISSUE THREAD

**Issue by ahmad-diaa** [JSTech2020/groups_de#23]
I have created a basic development in order to have everything locally during development using docker. What do you think about adding it to the develop branch so others can use it?

It would save the time wasted in communicating over s3 permissions and stuff like that. In addition to having the database up and running without doing any installations and directly getting rid of it when development is over.

cc @kylehiroyasu @dimitrityan @EdinCitaku @daliamaarek @klarmannsonia @ga58noc

**Comment by daliamaarek** [comment]
@ahmad-diaa sounds like a good idea 👍

**Comment by EdinCitaku** [comment]
Can we add the IP and port of our backend server as environment variables to our dockerfile? I think that would be the best way for our frontend to know where in what way to access the backend api.

**Comment by ahmad-diaa** [comment]
> Can we add the IP and port of our backend server as environment variables to our dockerfile? I think that would be the best way for our frontend to know where in what way to access the backend api.

Actually I didn't dockerize the app itself, but I am pro the idea of moving all connection strings and such stuff to a separate config file. You could check the environment here https://github.com/JSTech2020/groups_de/tree/feature/create-development-environment/development

This issue is to discuss the idea itself and if it's acceptable by most of the people we could suggest modifications.

**Comment by EdinCitaku** [comment]
Oh ok, yeah that makes sense. We can def do that. What do u think about containerizing the apps themselves? Should be pretty simple to do for our current case.

**Comment by ahmad-diaa** [comment]
> Oh ok, yeah that makes sense. We can def do that. What do u think about containerizing the apps themselves? Should be pretty simple to do for our current case.

Yeah, that makes sense. I have already containerized the backend app. I prefer postponing dockerizing the frontend app until I am more familiar with the code there.
